FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/.output /app
COPY --from=builder /app/node_modules /app/node_modules

EXPOSE 3000

CMD ["node", "server/index.mjs"]
